version: 2
jobs:
  build_client:
    docker:
      - image: circleci/node:10.11
    working_directory: ~/workspace
    steps:
      - checkout
      - restore_cache:
          keys:
          - otrace-client-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - otrace-client-dependencies-
      - run:
          name: yarn-install
          command: yarn install
      - save_cache:
          key: otrace-client-dependencies-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: yarn-eslint
          command: yarn eslint
      - run:
          name: yarn-build
          command: yarn build
  build_server:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    working_directory: ~/workspace
    steps:
      - checkout
      - restore_cache:
          key: otrace-web-dependencies-{{ checksum "build.gradle" }}
      - run:
          name: web-build
          command: ./gradlew clean build
      - save_cache:
          paths:
            - ~/.gradle
          key: otrace-web-dependencies-{{ checksum "build.gradle" }}
workflows:
  version: 2
  workflow:
    jobs:
      - build_client
      - build_server
